INSERT INTO `Latas` (`id_lata`, `nome`, `id_marca`, `id_tamanho`, `descontinuada`, `disponivel_portugal`, `notas`) VALUES
(1, 'Monster Energy Assault', 1, 1, 1, 0, 'Existiram duas versões desta lata, ambas hoje descontinuadas'),
(2, 'Monster Energy Ultra Violet', 1, 1, 0, 1, 'Sem nota'),
(3, 'Monster Energy Juiced Ripped', 1, 1, 1, 1, 'Sem notas'),
(4, 'Monster Energy Ultra Red', 1, 1, 1, 1, 'Sem notas'),
(5, 'Monster Energy Ultra Watermelon', 1, 1, 0, 1, 'Sem notas'),
(6, 'Monster Energy Zero Sugar NE', 1, 1, 0, 1, 'A sigla NE refere-se a New Edition'),
(7, 'Monster Energy Juiced Monarch', 1, 1, 0, 1, 'Prevista uma futura descontinuação'),
(8, 'Monster Energy Punch Pipiline Punch', 1, 1, 0, 1, 'Sem notas'),
(9, 'Monster Energy Ultra Rosa', 1, 1, 1, 0, 'Sem notas'),
(10, 'Monster Energy Ultra Peachy Keen', 1, 1, 0, 1, 'Sem notas'),
(11, 'Monster Energy Juiced Aussie Lemonade', 1, 1, 0, 0, 'Sem notas'),
(12, 'Monster Energy Lando Norris SE', 1, 1, 1, 0, 'A sigla SE refere-se a Special Edition'),
(13, 'Monster Energy Punch Rio Punch', 1, 1, 0, 1, 'Sem notas'),
(14, 'Monster Energy Expresso', 1, 2, 0, 1, 'Sem notas'),
(15, 'Monster Energy Export', 1, 2, 0, 1, 'Sem notas'),
(16, 'Monster Energy Lewis Hamilton FE', 1, 1, 1, 0, 'A sigla FE refere-se a First Edition'),
(17, 'Monster Energy Mulle Ginger Brew', 1, 1, 0, 0, 'Sem notas'),
(18, 'Monster Energy Ultra Fiesta', 1, 1, 1, 0, 'Apesar de uma vez descontinuada, esta lata já voltou ao mercado, sendo descontinuada novamente'),
(19, 'Monster Energy Juiced Bad Apple', 1, 1, 0, 1, 'Sem Notas'),
(20, 'Monster Energy Ultra Paradise', 1, 1, 0, 1, 'Sem Notas'),
(21, 'Monster Energy Hydrosports', 1, 3, 0, 0, 'Sem Notas'),
(22, 'Monster Energy MIXXD', 1, 1, 1, 0, 'Sem Notas'),
(23, 'Monster Energy Golden Pineapple', 1, 1, 1, 0, 'Sem Notas'),
(24, 'Monster Energy Ultra Strawberry Dreams', 1, 1, 0, 0, 'Sem notas'),
(25, 'Monster Energy The Doctor VR/46', 1, 1, 1, 0, 'Sem notas'),
(26, 'Monster Energy Reverse Watermelon', 1, 1, 0, 1, 'Sem notas'),
(27, 'Monster Energy Mega', 1, 3, 0, 1, 'Sem notas'),
(28, 'Monster Energy Juiced Khaotic', 1, 1, 0, 1, 'Sem notas'),
(29, 'Monster Energy Zero Sugar Blue Edition', 1, 1, 1, 0, 'A primeira edição de uma versão zero açucar'),
(30, 'Monster Energy Punch Pacific Punch', 1, 1, 0, 1, 'Sem notas'),
(31, 'Monster Energy Rehab Lemonade', 1, 1, 0, 1, 'Sem Notas'),
(32, 'Monster Energy Nitro Super Dry', 1, 1, 0, 1, 'Sem notas'),
(33, 'Monster Energy Lewis Hamilton NE', 1, 1, 1, 0, 'A sigla NE refere-se a New Edition'),
(34, 'Monster Energy Juiced Mango Loco', 1, 1, 0, 1, 'Sem Notas'),
(35, 'Monster Energy Juiced Mamgo Loco', 1, 2, 0, 1, 'Sem notas'),
(36, 'Monster Energy Ultra White', 1, 1, 0, 1, 'Sem notas'),
(37, 'Monster Energy Rehab Peach', 1, 1, 0, 1, 'Sem notas'),
(38, 'Monster Energy Reverse White Pineapple', 1, 1, 0, 1, 'sem notas'),
(39, 'Monster Energy Java Kona Blend', 1, 1, 0, 0, 'Sem notas'),
(40, 'Energy Drink Berries', 2, 1, 0, 1, 'Marca do Mercadona'),
(41, 'Energy Drink Furious', 2, 1, 0, 1, 'Marca do Mercadona'),
(42, 'Energy Drink Watermelon', 2, 1, 0, 1, 'Marca do Mercadona'),
(43, 'Energy Drink Full Tropic', 2, 1, 0, 1, 'Marca do Mercadona'),
(44, 'Energy Drink Sunset', 2, 1, 0, 1, 'Marca do Mercadona'),
(45, 'Energy Drink Katrine', 2, 1, 0, 1, 'Marca do Mercadona');